### ISSUE TITLE
Can we make "schema_version" a required tag?

### ISSUE THREAD

**Issue by kurtseifried** [ossf/osv-schema#116]
Can we make "schema_version" a required tag? Currently I have to brute force it by applying schemas until one passes, and it also makes identifying the files tricky.

**Comment by oliverchang** [comment]
Hey @kurtseifried , this is already a required field for all OSV entries > version 1.0.0 per https://ossf.github.io/osv-schema/#schema_version-field

We can't go back and enforce this for 1.0.0 unfortunately, as that would break compatibility.

**Comment by kurtseifried** [comment]
Sorry I think I'm not saying this clearly, I mean making the schema_version required, e.g. the docs currently say:

https://ossf.github.io/osv-schema/

The id and modified fields are required. All other fields are optional, although of course an entry with no other metadata is not particularly useful. (It could potentially stand for a reserved ID with no other public information.)

And in https://github.com/ossf/osv-schema/blob/main/validation/schema.json

  "required": [
    "id",
    "modified"
  ]
}

So you can have an OSV file without a schema_version tag. I'm talking about making it mandatory in a future version so that I don't have to apply schemas and guess which version a file is (or worse, it validates against 1.3.0 but was meant to be 1.4.0 and is missing something)

**Comment by oliverchang** [comment]
Ah, good catch.  We can update the text here to say that a `schema_version` field is required if targeting >  version 1.0.0. Would you mind opening a PR? Or I can do that as well. 

For the JSON validation, it's technically not correct to require the `schema_version` to be set, as it's not required for older entries that are 1.0.0, and the schema validator should validate all versions prior to the current release.

**Comment by kurtseifried** [comment]
This would have to be a forwards change, e.g. 1.5.0, we can't make it retroactive without potentially breaking data (e.g. someone using 1.4.0 with no schema_version tag).

**Comment by oliverchang** [comment]
It's actually already explicit requirement to have a schema_Version >1.0.0 per https://ossf.github.io/osv-schema/#schema_version-field. There was just a bug in the documentation that didn't explicitly state this in the part that you pointede out :)

**Comment by oliverchang** [comment]
I've uploaded https://github.com/ossf/osv-schema/pull/122 to address this.
