### ISSUE TITLE
What does an "introduced" value of "0" mean?

### ISSUE THREAD

**Issue by kurtseifried** [ossf/osv-schema#124]
From: https://ossf.github.io/osv-schema/

Special values
"introduced" allows a version of the value "0" to represent a version that sorts before any other version.

What does 0 mean? "since forever"? "unknown"? Something else?  Right after we have:

"limit" allows versions containing the string "*" to represent “infinity”. If no limit events are provided, an implicit { "limit": "*" } is assumed to exist. Multiple "limit" events are allowed in the same range.

So I assume 0 is meant to assume the inverse, or "forever", but for example, this breaks in the common case where the code has NOT been present in the given software since "forever" (e.g. the Linux Kernel, a lot of security fixes are for code added in the last decade, not earlier). Can we please clearly define what the "0" means?

**Comment by oliverchang** [comment]
"0" can be thought of as "the beginning of time" for the purposes of evaluating if a given version if affected by the advisory. 

Whether if this means "unknown", or if it actually means from the very first version is not encoded here. The intention is to enable unambiguous, clear automatable steps for our [evaluation algorithm](https://ossf.github.io/osv-schema/#evaluation) to determine if a given package and version is vulnerable according to an OSV advisory. 

The current definition: `"introduced" allows a version of the value "0" to represent a version that sorts before any other version.`, fits right into our evaluation algorithm. 

For your given example of Linux kernel vulnerabilities affecting code recently added: this is an interesting case, but I'm not sure if this is one that can be addressed by the schema. I think this would have to come down to better automation to set a better `introduced` field to reflect when the vulnerable was actually added.

**Comment by kurtseifried** [comment]
Right, so can you add this to the documentation? Because it's clear it is a special case, but not what the special is meant to be or exactly how it is meant to be used (just assume forever? are we supposed to go investigate and actually track it down? both?).

**Comment by andrewpollock** [comment]
> Right, so can you add this to the documentation?

https://ossf.github.io/osv-schema/#special-values already discusses this and looks like it's been present in the documentation for quite some time, so I think we can close out this issue?

**Comment by kurtseifried** [comment]
"introduced allows a version of the value "0" to represent a version that sorts before any other version."

What exactly does that mean? Every version is affected?

**Comment by oliverchang** [comment]
> "introduced allows a version of the value "0" to represent a version that sorts before any other version."
> 
> What exactly does that mean? Every version is affected?

Put in the context of the https://ossf.github.io/osv-schema/#affectedrangesevents-fields section that this is part of, this is what it means. There's also the https://ossf.github.io/osv-schema/#examples section which is also linked from the same section.

I don't think it makes sense to expand on this in the context of where it is.
