### ISSUE TITLE
Missing reference type value - the inverse of "FIX"

### ISSUE THREAD

**Issue by kurtseifried** [ossf/osv-schema#125]
So for reference types we have:

FIX: A source code browser link to the fix (e.g., a GitHub commit) Note that the fix type is meant for viewing by people using web browsers. Programs interested in analyzing the exact commit range would do better to use the GIT-typed affected[].ranges entries (described above).

But we have no inverse, no "INTRODUCED", and for many of these vulnerabilities we have the commit/change/issue/pull/etc that introduced the vulnerability, but no way to label it as such. I would like to simply suggest we add "INTRODUCED" as the inverse of "FIX" for the reference types.

**Comment by oliverchang** [comment]
Thanks! That seems like a reasonable addition!

**Comment by andrewpollock** [comment]
Can this be closed?
