### ISSUE TITLE
Missing endpoint to serve schema files as application/schema+json

### ISSUE THREAD

**Issue by kurtseifried** [ossf/osv-schema#126]
When embedding the OSV schema into another schema using $ref we get an error:

Error: https://raw.githubusercontent.com/ossf/osv-schema/v1.3.1/validation/schema.json is not a schema. Found a document with media type: text/plain

https://raw.githubusercontent.com/ossf/osv-schema/v1.3.1/validation/schema.json serves as text plain which fails: it needs to be served as "application/schema+json"

is there some official endpoint at osv.dev for example that serves the various schema files as application/schema+json?

If there already is one I apologize, I couldn't find it.

**Comment by oliverchang** [comment]
Unfortunately we don't. Thanks for filing this -- I've filed https://github.com/google/osv.dev/issues/1166 in response to this, and will close this in favour of that one.
