### ISSUE TITLE
OSV v1.0.0 is missing a canonical URL

### ISSUE THREAD

**Issue by joshbuker** [ossf/osv-schema#139]
Discovered this while discussing #132 

Currently, the canonical url for the schema is:
`https://raw.githubusercontent.com/ossf/osv-schema/v<SEMVER>/validation/schema.json`

For example, `1.4.0` resolves to:
https://raw.githubusercontent.com/ossf/osv-schema/v1.4.0/validation/schema.json

`1.0.0` is historically important due to `schema_version` being null is implied to be `1.0.0`, however currently that 404s:
https://raw.githubusercontent.com/ossf/osv-schema/v1.0.0/validation/schema.json

This should be added or backported so that it is consistent and can be used by validators.

**Comment by andrewpollock** [comment]
Looks like this is a case of releasing https://github.com/ossf/osv-schema/releases/tag/1.0.0

**Comment by oliverchang** [comment]
I've made a v1.0.0 release and https://raw.githubusercontent.com/ossf/osv-schema/v1.0.0/validation/schema.json now works.

**Comment by puerco** [comment]
A v1.0.0 release always warrants one or more beers :clinking_glasses:
