### ISSUE TITLE
Trying to understand why last_affected and fixed are exclusionary?

### ISSUE THREAD

**Issue by kurtseifried** [ossf/osv-schema#146]
In the schema:

                {
                  "if": {
                    "properties": {
                      "events": {
                        "contains": {
                          "required": ["last_affected"]
                        }
                      }
                    }
                  },
                  "then": {
                    "not": {
                      "properties": {
                        "events": {
                          "contains": {
                            "required": ["fixed"]
                          }
                        }
                      }
                    }
                  }
                }

Why are they exclusionary? I couldn't find anything in the docs. Was there a discussion about this that I can view that explains it?

**Comment by kurtseifried** [comment]
Or was it meant to have all 4 in there as per:

Only **a single type** (either `"introduced"`, `"fixed"`, `"last_affected"`,
`"limit"`) is allowed in each event object. For instance,
`{"introduced": "1.0.0", "fixed": "1.0.2"}` is **invalid**.

**Comment by oliverchang** [comment]
This is this sentence in the schema:

"Entries in the events array can contain either "last_affected" or "fixed" events, but not both."

The intention is to prevent confusing combinations of last_affected and fixed within the same `events` array, because they make each other redundant.

**Comment by kurtseifried** [comment]
Ok, can we update the docs to mention that this is actually enforced in the schema?

**Comment by bagder** [comment]
Why can't we have both? As a mere human, I think they provide information and it certainly doesn't *hurt* to have both even if one of them would suffice.

**Comment by andrewpollock** [comment]
@kurtseifried I'm trying to determine if there's anything actionable here. 

Are you asking to more explicitly state that things documented as being required by the schema are enforced by the schema definition?

**Comment by kurtseifried** [comment]
> @kurtseifried I'm trying to determine if there's anything actionable here.
> 
> Are you asking to more explicitly state that things documented as being required by the schema are enforced by the schema definition?

At a minimum, it needs to be documented, and enforced in the schema, so those both need an update.

Also, I think, in line with @bagder it is not necessary to make it exclusionary especially as there are many cases where "The intention is to prevent confusing combinations of last_affected and fixed within the same events array, because they make each other redundant." is not correct (Cisco software train version, Linux Kernel, etc.).

**Comment by andrewpollock** [comment]
> At a minimum, it needs to be documented, and enforced in the schema, so those both need an update.

I think the point @oliverchang was trying to make was that these are both the case today, if I am reading correctly?

Perhaps you could send us a PR to illustrate what you feel needs to be updated?

**Comment by kurtseifried** [comment]
The problem is, if it is up to me I would remove the requirement entirely and allow both. As such I can't really say why it is required, so I can't really submit a PR for this as I don't understand what the intent is other than "it might be confusing"(but for many of my use cases it is not).

**Comment by hayleycd** [comment]
For any future readers on this issue, please refer to [this comment](https://github.com/ossf/osv-schema/issues/150#issuecomment-1601930082) in #150 for clarity.

**Comment by hayleycd** [comment]
I think we can close this given #174 and #159
