### ISSUE TITLE
Missing escape in CVS v3

### ISSUE THREAD

**Issue by kurtseifried** [ossf/osv-schema#163]
"pattern": "CVSS:3\\.[0-9]/AV:[NALP]\\/AC:[LH]\\/PR:[NLH]\\/UI:[NR]\\/S:[UC]\\/C:[NLH]\\/I:[NLH]\\/A:[NLH]"

should be                   "pattern": "CVSS:3\\.[0-9]\\/AV:[NALP]\\/AC:[LH]\\/PR:[NLH]\\/UI:[NR]\\/S:[UC]\\/C:[NLH]\\/I:[NLH]\\/A:[NLH]"

fixed in a PR.

But more worryingly this indicates a lack of test data/harness, is there a test harness/data somewhere outside of this repo?

**Comment by kurtseifried** [comment]
https://github.com/ossf/osv-schema/pull/164

**Comment by andrewpollock** [comment]
> But more worryingly this indicates a lack of test data/harness, is there a test harness/data somewhere outside of this repo?

Not to my knowledge, @oliverchang ?

I think we can call this specific issue resolved by #165
