### ISSUE TITLE
Missing CVSSv4 support

### ISSUE THREAD

**Issue by kurtseifried** [ossf/osv-schema#167]
https://www.first.org/cvss/v4.0/specification-document

CVSS:4\\.[0-9]\\/AV:[NALP]\\/AC:[LH]\\/AT:[NP]\\/PR:[NLH]\\/UI:[NPA](\\/VC:[HLN]\\/VI:[HLN]\\/VA:[HLN]\\/SC:[HLN]\\/SI:[HLN]\\/SA:[HLN])\\/S:[XNP]\\/AU:[XNY]\\/R:[XAUI]\\/V:[XDC]\\/RE:[XLMH]\\/U:[XCGAR]\\/MAV:[XNALP]\\/MAC:[XLH]\\/MAT:[XNP]\\/MPR:[XNLH]\\/MUI:[XNPA]\\/:MVC[XHLN]\\/:MVI[XHLN]\\/:MVA[XHLN]\\/:MSC[XHLN]\\/:MSI[XSHLN]\\/:MSA[XSHLN]\\/:CR[XHML]\\/:IR[XHML]\\/:AR[XHML]\\/:E[XAPU]

I suggest we leave "Vulnerable System Impact Metrics" and "Subsequent System Impact Metrics" as optional for now, but linked, as we can't know those. It should be noted that ideally vendors with specific products should add this data. However as all the other fields have a "Not Defined" option I think we should make them mandatory (and people can simply put "Not Defined").

https://github.com/ossf/osv-schema/pull/166

**Comment by oliverchang** [comment]
This was added in https://github.com/ossf/osv-schema/commit/463720c3fff0692dde0a8f3d69eb8d282e09332b.
