### ISSUE TITLE
Support Debian advisories

### ISSUE THREAD

**Issue by oliverchang** [ossf/osv-schema#24]
Moving discussion from https://github.com/ossf/osv-schema/pull/10.

**Comment by oliverchang** [comment]
@rhertzog @jeremiah @pombredanne Moving our discussion from https://github.com/ossf/osv-schema/pull/10 and coming back on this thread once more. I really apologize for the delay -- I really need to fix my GitHub email filters. 

To answer some questions from the last comment:

> What kind of generic tools are you referring too? How would they consume this data?

These would be SBOM (e.g. CycloneDX, SPDX) generator tools (which e.g. generate this from a container image) and generic vulnerability scanner / matchers which take an SBOM or similar as input. Typically these work at a binary package level so having this list of binary packages will make things much easier. Our goal with the OSV schema is to define a generic format for describing vulnerabilities that plugs into generic tooling like these without users having to understand the details of the ecosystem.

The size of the submitted data will increase, yes, but this shouldn't be a problem as they're being consumed by automated scanners and vulnerability matchers. 

Are the existing [Debian advisories](https://www.debian.org/security/2021/) available in a machine parseable format anywhere? We'd be happy to convert a few entries manually to show what these would look like, and  help build tooling to expand / convert these from existing DSA entries.

**Comment by rhertzog** [comment]
> Typically these work at a binary package level so having this list of binary packages will make things much easier. 

If they do get list of Debian binary packages, they already access the dpkg database and in that case, it's just as convenient to extract the source package name from the database. It's just another field in the same file. Or another query to dpkg-query.

We should not make it convenient for tools that consume the data, but for humans that build and maintain the database. tools can be improved and will not complain about the extra step.

> Are the existing Debian advisories available in a machine parseable format anywhere?
Our security data is managed in the security tracker: https://security-tracker.debian.org/tracker/
Most of the data is in text files in a git repository: https://salsa.debian.org/security-tracker-team/security-tracker/-/blob/master/data/DSA/list

But we have some JSON export built by the security tracker: https://security-tracker.debian.org/tracker/data/json (beware it's big)

**Comment by oliverchang** [comment]
> If they do get list of Debian binary packages, they already access the dpkg database and in that case, it's just as convenient to extract the source package name from the database. It's just another field in the same file. Or another query to dpkg-query.

Ideally yes! But there may be strange contexts from which tools generating an SBOM may not have access to the full dpkg database. e.g. if this was generated from `.deb` files lying around on a filesystem -- would it be possible to tell what the source package was? 

> 
> We should not make it convenient for tools that consume the data, but for humans that build and maintain the database. tools can be improved and will not complain about the extra step.

Completely agree on making it easy for humans to build and maintain the advisory database! For the OSV format itself, it doesn't have to be the human editable format that it's maintained in (but ideally it can be). It simply needs to be an exported format for other tools and services to consume. 

> 
> > Are the existing Debian advisories available in a machine parseable format anywhere?
> 
> Our security data is managed in the security tracker: https://security-tracker.debian.org/tracker/ Most of the data is in text files in a git repository: https://salsa.debian.org/security-tracker-team/security-tracker/-/blob/master/data/DSA/list
> 
> But we have some JSON export built by the security tracker: https://security-tracker.debian.org/tracker/data/json (beware it's big)

Thanks!! We'll take a look and try to prototype what an OSV export might look like.

**Comment by rhertzog** [comment]
>  if this was generated from .deb files lying around on a filesystem -- would it be possible to tell what the source package was?

Yes, of course, the dpkg database is mainly a concatenation of the data available in the .deb files that have been installed (`dpkg -I foo.deb control` gives you the relevant data with the Package field and the optional Source field - only set when source name is different from Package).

> It simply needs to be an exported format for other tools and services to consume.

Right. But it does mean that an OSV export would be useful only for a single Debian release, the one that served as reference for turning source packages into binary packages. So we would have multiple OSV exports, one for each Debian release.

**Comment by oliverchang** [comment]
Some initial investigation/updates:
- https://salsa.debian.org/security-tracker-team/security-tracker/-/blob/master/data/DSA/list has machine readable mappings to versions, but seems to lack detailed text descriptions.
- https://salsa.debian.org/webmaster-team/webwml/-/tree/master/english/security/2022 has other detailed metadata we could parse.

Perhaps combining the two would be the best approach? 

Other observations:
- https://salsa.debian.org/security-tracker-team/security-tracker/-/blob/master/data/DSA/list has fix info (upper bound) per distro, but no lower bound (i.e. which version first had the vulnerability). We'd have to figure out the lower bound ourselves from somewhere (taking the first released version in the relevant distro?)

More to come later.

**Comment by oliverchang** [comment]
We're finally starting work on this now. @rhertzog  we have a few questions if you don't mind?

1. We're going to start with combining data from both the security-tracker repo (for version information) and the webwml repo (for text descriptions + other metadata like timestamps). Is this the best way to go about this?

2. For versioning, we're going to start with source package names as @rhertzog initially suggested.

    We have additional questions though, around tracking affected versions across different releases. There are two alternatives using a fictional example of a vulnerability in libxml2 that's
  
    - Fixed in 1.10.0~deb9u1 in stretch (Debian 9)
    - Fixed in 1.15.0~deb10u1 in buster (Debian 10)

### Alternative 1 (Single unified "Debian" namespace).

```json
{
  "package": {"name": "libxml2", "ecosystem": "Debian"},
  "ranges": {
    "type": "ECOSYSTEM",
    "events": [
      { "introduced": "1.10.0" }, # or whatever the first version in stretch is.
      { "fixed": "1.10.0~deb9u1"},
      { "introduced": "1.15.0" }, # or whatever the first version in buster is.
      { "fixed": "1.15.0~deb10u1"},
    ],
  }
}
```

Pros:
- This reduces duplication 
- Being agnostic to particular releases, this can potentially help catch vulnerable packages in non-stable versions of Debian.
- This fits with the model of Debian packages being in a unified pool. 

Cons:
- This requires us to figure out what the first version of a package is within a release. This seems particularly difficult. 
- Can these version ranges (introduced/fixed) overlap between different Debian release? This would be very confusing to consumers of this data. 

### Alternative 2 (Single unified "Debian" namespace).
```json
[
  {
    "package": {"name": "libxml2", "ecosystem": "Debian:9"},
    "ranges": {
      "type": "ECOSYSTEM",
      "events": [
        { "introduced": "0" }, # 0 means the first version in the namespace/package
        { "fixed": "1.10.0~deb9u1"},
      ],
    }
  },
  {
    "package": {"name": "libxml2", "ecosystem": "Debian:10"},
    "ranges": {
      "type": "ECOSYSTEM",
      "events": [
        { "introduced": "0" }, # 0 means the first version in the namespace/package
        { "fixed": "1.15.0~deb10u1"},
      ],
    }
  },
]
```

Pros:
- This matches more closely how Debian advisories are tracked

Cons:
- This results in some repetition / bigger advisory sizes. 
- Debian packages live in a unified pool -- does it make sense to split packages up by releases? 

@rhertzog which approach makes the most sense here to you?

**Comment by rhertzog** [comment]
Replying to a pro listed for the first alternative:
> Being agnostic to particular releases, this can potentially help catch vulnerable packages in non-stable versions of Debian.

Note that the second approach doesn't forbid us to have a "Debian:unstable" namespace covering testing+unstable, we have the required information in the security tracker. So it's not such a big advantage.

**Comment by westonsteimel** [comment]
I'm also in favour of the second approach.

> Scanners/SBOMs would have to keep track of the Debian release

Anchore at least already takes this approach and I'm fairly sure trivy does as well

**Comment by westonsteimel** [comment]
In fact, the current grype namespaces for debian vulnerabilities are exactly:
```
debian:7 
debian:8
debian:9
debian:10
debian:11
debian:12
debian:unstable
```

**Comment by pombredanne** [comment]
IMHO considering that the Debian release is required in a package namespace and being a part of the  package identification is incorrect and a source of problems for downstream users.

Why? Primarily because I cannot infer the Debian release just by looking at a package alone and I would need to make either an unreliable guess or do some external lookup.

- I can install a Debian package version possibly compiled and/or intended for deployment on release 10 on release 8. So I cannot rely on os-wide settings (such as say an /etc/os-release) to determine the actual intended release of a package as these may not match.

- Some package may have a version suffix such as  `deb10` and that looks like a Debian release. But these may not match the current OS release where the package is installed either (see point above).

- The Debian release is not part of what identifies a package at Debian itself: only the package name and version matters and that's the only key in the pool. At best it is an optional qualifier.

(As a side note --which is not a problem exclusive to Debian-- you cannot actually "find" where a Debian package archives live short of iterating all the source's indexes)

In conclusion, this is an arbitrary identifier from a vulnerability and package id point of vue and not even used by Debian to identify their own packages: Given a Debian package and version, knowing which release it is intended for does not help me to find it anymore than its name/version alone. 

Arbitrarily assigned identifiers has defined CPEs (and has been their curse) and should be best avoided when possible.

**Comment by rhertzog** [comment]
> IMHO considering that the Debian release is required in a package namespace and being a part of the package identification is incorrect and a source of problems for downstream users.

We are not describing packages here, we are describing vulnerabilities and vulnerabilities are dealt differently in different debian releases, you can't ignore that fact.

Yes, if you pick a random Debian package, you can't know what Debian release it targets, and where it comes from. But when you inspect a Debian server, you can lookup which APT source is providing the package (or you might conclude that it comes from somewhere else) and that APT source has a Release file with details like the version of Debian.

But I fail to see the connection with this discussion.

**Comment by another-rex** [comment]
Just working on this with @oliverchang, and I am currently having trouble finding an automated way to get the index of release numbers mapped to their codenames. 

I am essentially looking for the information on https://www.debian.org/releases/ but in the form of an API. Would you @rhertzog  happen to know of any endpoint like that?

**Comment by rhertzog** [comment]
On Thu, 09 Jun 2022, Rex P wrote:
> I am essentially looking for the information on
> https://www.debian.org/releases/ but in the form of an API. Would you
> @rhertzog  happen to know of any endpoint like that?

Not really an API per se, but have a look at:
https://salsa.debian.org/debian/distro-info-data

In particular it points to https://debian.pages.debian.net/distro-info-data/debian.csv

Cheers,
-- 
  ⢀⣴⠾⠻⢶⣦⠀   Raphaël Hertzog ***@***.***>
  ⣾⠁⢠⠒⠀⣿⡁
  ⢿⡄⠘⠷⠚⠋    The Debian Handbook: https://debian-handbook.info/get/
  ⠈⠳⣄⠀⠀⠀⠀   Debian Long Term Support: https://deb.li/LTS

**Comment by oliverchang** [comment]
Debian is supported now through our custom converter. See  e.g. https://osv.dev/vulnerability/DSA-5221-1
