### ISSUE TITLE
Add support for SUSE and openSUSE

### ISSUE THREAD

**Issue by msmeissn** [ossf/osv-schema#259]
This issue tracks addition of SUSE and openSUSE.

**Comment by andrewpollock** [comment]
Long time no hear @msmeissn, excited to see this progress. I hope you're well.

**Comment by oliverchang** [comment]
I've opened https://github.com/google/osv.dev/issues/2543 to track the osv.dev ingestion side of this.

**Comment by oliverchang** [comment]
(And seeing as there's nothing left for the schema, I'm closing this!)
