### ISSUE TITLE
Pylint alerts corrections as part of intervention experiment 

### ISSUE THREAD

**Issue by evidencebp** [ossf/osv-schema#290]
I'd like to conduct a software engineering experiment regarding the benefit of Pylint alerts removal.
The experiment is described [here](https://github.com/evidencebp/pylint-intervention/).
In the experiments, Pylint is used with some specific alerts, files are selected for intervention and control.
After the interventions are done, one can wait and examine the results.

I'm asking your approval for conducting the interventions in your repositories.The interventions are expected to benefit the project and will submitted in PR for approval.

The specific intervention is the removal of the "Too many branches" in tools\ghsa\convert_ghsa.py in the function get_affected.
This can be done by extracting some of the logic into separate functions.

@oliverchang @calebbrown, I noted that you wrote the file.
Is it OK if I'll fix this alert?

**Comment by andrewpollock** [comment]
This seems fine to send a PR for, thank you for addressing this code smell

**Comment by evidencebp** [comment]
Actually, I see that someone already fixed the only alert you had there.
good for you and thank you for the willingness to help!
