### ISSUE TITLE
affected ranges are order dependent

### ISSUE THREAD

**Issue by neild** [ossf/osv-schema#44]
The algorithm for evaluating if a package/version is affected by a vulnerability (https://ossf.github.io/osv-schema/#evaluation) is dependent on the order of ranges. It doesn't look like this is intentional.

```
func IncludedInRanges(v, ranges)
  vulnerable = false
  for range in ranges
    if BeforeLimits(v, range)
      for evt in sorted(range.events)
        if evt.introduced is present && v >= evt.introduced
           vulnerable = true
        else if evt.fixed is present && v >= evt.fixed
           vulnerable = false
        else if evt.last_affected is present && v > evt.last_affected
           vulnerable = false

  return vulnerable
```

If we have:

```
"ranges": [ {
    "type": "SEMVER",
    "events": [
      { "introduced": "1.1.0" },
      { "fixed": "1.1.3" },
    ]
}, {
    "type": "SEMVER",
    "events": [
      { "introduced": "0" },
      { "fixed": "1.0.2" },
    ]
} ]
```

Then according to this algorithm, 1.1.0 is not vulnerable: The first iteration of `for range in ranges:` sets `vulnerable=true`, the second iteration if sets `vulnerable=false`, and the function returns `false`.

I think there may be an implicit assumption that there will be only one range of a given type, but I can't find any such restriction in the spec. Perhaps I'm overlooking it. Even if there is such a restriction, however, it seems like `IncludedInRanges` should return true if *any* range matches the given version.

**Comment by rsc** [comment]
I agree: this looks like a bug. I believe the correct algorithm is:

```
func IncludedInRanges(v, ranges) {
    for range in ranges {
        if BeforeLimits(v, range) {
            vulnerable = false
            for evt in sorted(range.events) {
                if evt.introduced is present && v >= evt.introduced
                    vulnerable = true
                else if evt.fixed is present && v >= evt.fixed
                    vulnerable = false
                else if evt.last_affected is present && v > evt.last_affected
                    vulnerable = false
            }
            if vulnerable
                return true
        }
    }
    return false
}
```

**Comment by oliverchang** [comment]
Thanks for catching this! I uploaded https://github.com/ossf/osv-schema/pull/45 to fix this (using @rsc's suggestion).
