### ISSUE TITLE
missing a way to specify affected/fixed version based on dates (e.g. for services)

### ISSUE THREAD

**Issue by kurtseifried** [ossf/osv-schema#62]
so I found a vuln in service, they fixed it, I updated the GSD entry:

https://github.com/cloudsecurityalliance/gsd-database/pull/2366

and realized there's no way to list a date.

affected[].ranges[].type field supports SEMVER/ECOSYSTEM/GIT, and an easy fix here would be to add TIME (suggested RFC 3339 format), so can we add that, specified as RFC 3339 format? Thanks

**Comment by kurtseifried** [comment]
TIME/DATE/TIMESTAMP, TIMESTAMP is probably best but I'm not that concerned. Just as long as it's RFC3339 formatted.

**Comment by oliverchang** [comment]
Thanks for opening this! 

The primary question we always ask ourselves when adding a new field is how this will be used by a consumer (in particular automation systems). 

How would we refer to the service in a consistent way in this case? This seems like the first problem to solve -- is this something we can solve by adding a say an

```json
{
  "ecosystem": "Service",
  "name": "blah.com"
} 
```

There are some open questions around normalization/consistency (which URL should be used etc? `blah.com` vs `https://blah.com/v1/blah` or any other variations?) What exactly consistutes a "Service"?  

Taking a step back from all this: for a consumer of these entries: what would be the action they're expected to take? For open source packages with patch versions, they need to update. It's unclear what a consumer should be doing here for service vulnerabilities.

**Comment by kurtseifried** [comment]
Well there's a number of ways:

URL to actual API endpoint for an affected API 

URL to the service in the admin panel or the description, e.g.: 
https://s3.console.aws.amazon.com/
https://aws.amazon.com/s3/

Or a simple text description (less ideal, but better than nothing)

**Comment by andrewpollock** [comment]
[CalVer](https://calver.org/) seems to be a reasonably well defined versioning format. I think this issue could be retitled/rescoped to requesting support for this as an additional `range` type?
