### ISSUE TITLE
Trying t track down all versions of OSV schema

### ISSUE THREAD

**Issue by kurtseifried** [ossf/osv-schema#80]
So according to: https://github.com/ossf/osv-schema/tags
We have 0.7.1, 1.0.0, 1.3.0

And according to https://github.com/ossf/osv-schema/releases
We have 0.7.1, 1.2.0 and 1.3.0

but the 1.2.0 file has a file path of "osv-schema-1.0.0"

So is 1.2.0 actually 1.0.0? I ask because GHSA's specifies 1.2.0 for OSV version.

**Comment by oliverchang** [comment]
Thanks! I'll fix this up and create the relevant tags/releases for all of them.

**Comment by oliverchang** [comment]
I've fixed up most of the tags on https://github.com/ossf/osv-schema/tags now.

**Comment by kurtseifried** [comment]
So to confirm the official versions so far are:

0.7.1, 1.0.0, 1.1.0, 1.2.0, 1.3.0

I don't see a dedicated schema file for 0.7.1 and 1.0.0, is that correct?

**Comment by oliverchang** [comment]
That's correct. We didn't have a JSON validator file back then.
