### ISSUE TITLE
Why is CVSS limited to CVSS v3.x?

### ISSUE THREAD

**Issue by kurtseifried** [ossf/osv-schema#84]
CVSS_V3 | A CVSS vector string representing the unique characteristics and severity of the vulnerability using a version of the Common Vulnerability Scoring System notation that is >= 3.0 and < 4.0 (e.g."CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:C/C:H/I:N/A:N").

Can we please either:

1) add CVSS_V2 tag for CVSS v2 data (e.g. historical stuff)
2) change CVSS_V3 to CVSS and simply specify the CVSS version in the string (as generally done). This also solves the "what about CVSS v4 problem in future?

**Comment by oliverchang** [comment]
Please propose a PR for the CVSS_V2 tag! That should be a very straightforward tag to add.

**Comment by kurtseifried** [comment]
Is there documentation on this? E.g. what do I need to actually change?

https://github.com/ossf/osv-schema/blob/main/validation/schema.json
https://github.com/ossf/osv-schema/blob/main/docs/schema.md

anything else?

**Comment by oliverchang** [comment]
That should be it.

**Comment by kurtseifried** [comment]
Ok done https://github.com/ossf/osv-schema/pull/86

**Comment by kurtseifried** [comment]
This one: https://github.com/ossf/osv-schema/pull/87

**Comment by oliverchang** [comment]
added in https://github.com/ossf/osv-schema/pull/87
