### ISSUE TITLE
What kind of credit in credits field?

### ISSUE THREAD

**Issue by kurtseifried** [ossf/osv-schema#85]
credits fields
{
	"credits": [ {
		"name": string,
		"contact": [ string ],
	} ]
}
The credits field is a JSON array providing a way to give credit for the discovery, confirmation, patch, or other events in the life cycle of a vulnerability.

is there some reason we don't have an optional text description or ENUM for what kind of credit(s)?

**Comment by KateCatlin** [comment]
Chiming in here from the GitHub side, we'd like to update our own credits model to have types of credits in alignment with [the MITRE spec](https://github.com/CVEProject/cve-schema/blob/master/schema/v5.0/CVE_JSON_5.0_schema.json#L997-L1006). 

Would be great if we could consider a "type" field in credits similar to the OSV references field.

**Comment by captn3m0** [comment]
How should package-maintainers get credited? `remediation developer` ?

**Comment by KateCatlin** [comment]
@captn3m0 here's how the meanings are described as per MITRE: 

> finder: identifies the vulnerability
> reporter: notifies the vendor of the vulnerability to a CNA.
> analyst: validates the vulnerability to ensure accuracy or severity.
> coordinator: facilitates the coordinated response process.
> remediation developer: prepares a code change or other remediation plans.
> remediation reviewer: reviews vulnerability remediation plans or code changes for effectiveness and completeness.
> remediation verifier: tests and verifies the vulnerability or its remediation.
> tool: names of tools used in vulnerability discovery or identification.
> sponsor: supports the vulnerability identification or remediation activities.

So I guess it would depend on the maintainer's role in the solution... Could be analyst, coordinator, remediation developer, or really any.

**Comment by oliverchang** [comment]
Would someone like to suggest a PR to add this? It seems like the type should enable an easy 1:1 mapping to MITRE for interoperability.

**Comment by KateCatlin** [comment]
@oliverchang thank you! Our team will submit one.

**Comment by hawaiigal** [comment]
@oliverchang created a PR here: https://github.com/ossf/osv-schema/pull/110

/cc @KateCatlin @katblag
