### ISSUE TITLE
Consider enforcing seconds-only precision for timestamps

### ISSUE THREAD

**Issue by andrewpollock** [ossf/osv-schema#97]
@woodruffw in https://github.com/google/osv.dev/issues/857 mentioned

> (Separately, I wonder if it might make sense to redefine the schema to enforce seconds-only precision -- having the microseconds in the `published` timestamp probably doesn't convey anything of value to most consumers and potentially makes naive timestamp comparison a little harder.)

**Comment by woodruffw** [comment]
Thanks for making an issue here!

**Comment by oliverchang** [comment]
Unfortunately we are generally very conservative about breaking changes like these in the schema and changing the meaning of fields. A client written to parse version 1.X should be able to parse any earlier minor/patch versions as well. Any breaking changes would require a new major version, which we'd like to avoid to avoid fragmentation.
