### ISSUE TITLE
The url is 404: https://storage.googleapis.com/cve-osv-conversion/osv-output/

### ISSUE THREAD

**Issue by ssst0n3** [ossf/osv-schema#99]
https://github.com/ossf/osv-schema/blob/5ffb0eb2f02d05836f2144d16fbe9e71a4f3c5ae/docs/schema.md?plain=1#L171

**Comment by another-rex** [comment]
Thanks for pointing this out! The correct URL for the full list should be `https://storage.googleapis.com/cve-osv-conversion/`, and to get individual OSV files: `https://storage.googleapis.com/cve-osv-conversion/osv-output/<ID>.json`
